check for build/library.make as well

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -81,11 +81,13 @@ else
 	fi
 fi
 if test ! -f "$MONO_SOURCE_PATH/class/library.make" ; then
-	AC_MSG_WARN(not found)
-	echo '*****************************************************************'
-	echo "Could not find the Mono library source in the specified location."
-	echo '*****************************************************************'
-	exit 1
+	if test ! -f "$MONO_SOURCE_PATH/build/library.make"; then
+		AC_MSG_WARN(not found)
+		echo '*****************************************************************'
+		echo "Could not find the Mono library source in the specified location."
+		echo '*****************************************************************'
+		exit 1
+	fi
 fi
 AC_MSG_RESULT($MONO_SOURCE_PATH)
 
