2007-02-19  Klaus Treichel  <ktreichel@web.de>
	* configure.in: Fix build on cygwin by moving the check for windows to the
	start in front of the check for programs so that the changed CC can be
	taken into account.

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -9,35 +9,8 @@ AM_INIT_AUTOMAKE(pnet, 0.7.5)
 AM_CONFIG_HEADER(include/il_config.h)
 AM_MAINTAINER_MODE
 
-dnl Checks for programs.
-AC_PROG_AWK
-AC_PROG_CC
-AC_PROG_CXX
-AC_PROG_INSTALL
-AC_PROG_LN_S
-AC_PROG_MAKE_SET
-AC_PROG_LIBTOOL
-AC_PROG_YACC
-AM_PROG_LEX
-
 # Tell everyone if we are crosscompiling
 AM_CONDITIONAL(CROSS_COMPILING, test $cross_compiling = yes)
-
-AC_PATH_PROG(TREECC, treecc,, ${prefix}/bin:$PATH)
-if test -z "$TREECC" ; then
-    echo "treecc is required to build and can be obtained from"
-    echo "http://www.southern-storm.com.au"
-    exit 1
-fi
-TREECC_VERSION=`"$TREECC" -v | (read name version rest; echo $version)`
-AC_SUBST(TREECC_VERSION)
-
-if test x$cross_compiling = xyes ; then
-	AC_PATH_PROG(ILASM, ilasm)
-else
-	ILASM="\$(top_builddir)/ilasm/ilasm"
-fi
-AC_SUBST(ILASM)
 
 AC_PATH_PROG(SYSTEM_AR, ar)
 
@@ -57,7 +30,7 @@ AC_ARG_ENABLE(cygwin,
   *) AC_MSG_ERROR(bad value ${enableval} for --enable-cygwin) ;;
 esac],[cygwin=$def_cygwin])
 if test x$cygwin = xfalse ; then
-  CC="$CC -mno-cygwin"
+  CC="gcc -mno-cygwin"
   # to pass -mno-cygwin to configure of libffi and libgc
   export CC
   SOCKETLIBS="-lwsock32"
@@ -74,6 +47,34 @@ else
 	*) ;;
   esac
 fi
+
+dnl Checks for programs.
+AC_PROG_AWK
+AC_PROG_CC
+AC_PROG_CXX
+AC_PROG_INSTALL
+AC_PROG_LN_S
+AC_PROG_MAKE_SET
+AC_LIBTOOL_WIN32_DLL
+AC_PROG_LIBTOOL
+AC_PROG_YACC
+AM_PROG_LEX
+
+AC_PATH_PROG(TREECC, treecc,, ${prefix}/bin:$PATH)
+if test -z "$TREECC" ; then
+    echo "treecc is required to build and can be obtained from"
+    echo "http://www.southern-storm.com.au"
+    exit 1
+fi
+TREECC_VERSION=`"$TREECC" -v | (read name version rest; echo $version)`
+AC_SUBST(TREECC_VERSION)
+
+if test x$cross_compiling = xyes ; then
+	AC_PATH_PROG(ILASM, ilasm)
+else
+	ILASM="\$(top_builddir)/ilasm/ilasm"
+fi
+AC_SUBST(ILASM)
 
 dnl Disable typed allocation with libgc.
 def_typedalloc=true
