Remove the "64.dll" and "32.dll" suffixes from the assemblies, as they are no longer necessary.

diff --git a/samples/ilrun.sh.in b/samples/ilrun.sh.in
--- a/samples/ilrun.sh.in
+++ b/samples/ilrun.sh.in
@@ -17,8 +17,8 @@ if test -f "$PNETLIB_PATH/runtime/mscorlib.dll" ; then
 	ILRUN_FLAGS="$ILRUN_FLAGS -L$PNETLIB_PATH/runtime"
 fi
 
-if ! test -f "../libc/libc@LIBRARY_SUFFIX@.dll" ; then
-	echo "$0: could not find libc@LIBRARY_SUFFIX@.dll" 1>&2
+if ! test -f "../libc/libc.dll" ; then
+	echo "$0: could not find libc.dll" 1>&2
 	exit 1
 fi
 
